
source 'https://rubygems.org' do
  gem 'sinatra', :require => ['sinatra','sinatra/reloader']
  gem 'sinatra-contrib'
  gem 'crack'
  group :development do
    require 'sinatra/reloader'
  end
  require 'open-uri'
  require 'pp'
end
